export const ADDPENDINGTODO = "ADDPENDINGTODO";
export const REMOVEPENDINGTODO = "REMOVEPENDINGTODO";
export const ADDCOMPLETEDTODO = "ADDCOMPLETEDTODO";
export const REMOVECOMPLETEDTODO = "REMOVECOMPLETEDTODO";
export const REMOVEALLCOMPLETED = "REMOVEALLCOMPLETED";

