export const ADDCOMPLETEDTODO = "ADDCOMPLETEDTODO";
export const ADDPENDINGTODO = "ADDPENDINGTODO";
export const REMOVECOMPLETEDTODO = "REMOVECOMPLETEDTODO";
export const REMOVEALLCOMPLETED = "REMOVEALLCOMPLETED";
export const REMOVEPENDINGTODO = "REMOVEPENDINGTODO";